### ISSUE TITLE
Read-only root filesystem for hastebin deployment

### ISSUE THREAD

**Issue by jchristgit** [python-discord/kubernetes#81]
via @jb3:

We need to clone the `haste-server` repository elsewhere, as the container will currently run from `/` and clone into `/haste-server`. Perhaps mounting a volume at `/haste-server` is enough.

Data is stored in Redis. My favourite database.

**Comment by jerbob** [comment]
> via @jb3:
> 
> We need to clone the `haste-server` repository elsewhere, as the container will currently run from `/` and clone into `/haste-server`. Perhaps mounting a volume at `/haste-server` is enough.
> 
> Data is stored in Redis. My favourite database.

No. Redis is not a database, it's an in-memory key-value store. It's also called a [distributed] data structure server, which (at least to me) implies a tight coupling with your application: it's a way to offload shared state between multiple components, but the persistence of that shared state is not guaranteed.

In fact, Redis' persistence layer is best understood as a best-effort value-add. If the server shuts down for any reason, you have to simply hope the last disk flush was recent and successful. Otherwise, your data is lost. This is (again, to me) fundamentally at odds with the contracts that any database should provide. Also, Redis cluster is not yet released, which means running more than one Redis server requires you to manage keyspace sharding at the app layer.

Not that any of this is a knock against Redis. Even with those caveats, there are a huge class of problems that Redis is perfectly suited for. I love the software and use it daily. But Redis competes with memcached, not MongoDB; if you ever find yourself shoe-horning Redis into a role where total data loss is anything other than temporarily annoying, you're doing it wrong.

**Comment by jb3** [comment]
Solved by #92

**Comment by jchristgit** [comment]
> Solved by #92

No. Redis is not a database, it's an in-memory key-value store. It's also called a [distributed] data structure server, which (at least to me) implies a tight coupling with your application: it's a way to offload shared state between multiple components, but the persistence of that shared state is not guaranteed.
